WebUI/Controllers/IdeasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Domain.Abstract;
using WebUI.Models;
using Domain.Entities;
using WebUI.Models.DbSelection;
using Ninject;
using WebUI.Auth;

namespace WebUI.Controllers
{
    public class IdeasController : Controller
    {
        [Inject]
         private IIdeasRepository repository;
        [Inject]
        IAuthentification auth;
        [Inject]
        private IDbSelector dbSelector;
         private int PageSize = 5;

         public IdeasController(IIdeasRepository ideasRepository, IAuthentification auth, IDbSelector dbSelector)
         {
             this.repository = ideasRepository;
             this.auth = auth;
             this.dbSelector = dbSelector;
         }

         protected override void Initialize(System.Web.Routing.RequestContext requestContext)
         {
             base.Initialize(requestContext);
             ViewBag.Author = CurrentAuthor;
         }

         public LoggedinAuthor CurrentAuthor
         {
             get
             {
                 auth.HttpContext = this.HttpContext.ApplicationInstance.Context;
                 var currentUser = auth.CurrentUser;
                 if (currentUser != null)
                 {
                     return ((UserIndentity)currentUser.Identity).User.ToLoggedinAuthor();
                 }
                 return null;
             }
         }

         public ViewResult IdeasList(int page = 1)
         {
             IdeasListViewModel model = dbSelector.GetIdeasList(repository, page, PageSize);
             return View(model);
         }

         public ViewResult IdeaPage(int ideaId)
         {
             Idea idea = dbSelector.GetIdea(repository, ideaId);

             return View(idea);
         }
         [HttpGet]
         public ViewResult UserPage(string login)
         {
             Author author = repository.GetAuthor(login);
             return View(author);
         }

         [HttpGet]
         public ActionResult MoveIdeaToTrash(int ideaId)
         {
             repository.MoveIdeaToTrash(ideaId);

             return RedirectToAction("IdeasList");
         }

         [HttpGet]
         public ActionResult CreateIdea()
         {
             return View("EditIdea", new Idea { UserId = CurrentAuthor.UserId, Date = DateTime.Now, Status = IdeaStatus.IS_ACTIVE });
         }

         [HttpGet]
         public ActionResult EditIdea(int ideaId)
         {
             Idea idea = dbSelector.GetIdea(repository, ideaId);

             return View(idea);
         }

         [HttpPost]
         public ActionResult EditIdea(Idea idea)
         {
             if (idea.UserId == CurrentAuthor.UserId)
             {
                 if (ModelState.IsValid)
                 {
                     repository.SaveIdea(idea);
                     return RedirectToAction("IdeasList");
                 }
                 else
                 {
                     return View(idea);
                 }
             }
             return RedirectToAction("IdeasList");
         }
    }
}

WebUI/Controllers/UserController.cs
using Domain.Abstract;
using Domain.Entities;
using Ninject;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Principal;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using System.Web.Security;
using WebUI.Auth;
using WebUI.Models;
using WebUI.Models.Ausorization;
using WebUI.Models.DbSelection;

namespace WebUI.Controllers
{
    [ModeratorAuthorize (Role.Administrator)]
    public class UserController : Controller
    {
        [Inject]
        private IIdeasRepository Repository { get; set; }
        [Inject]
        public IAuthentification Auth { get; set; }
        [Inject]
        public IDbSelector DbSelector { get; set; }
        public int PageSize = 20;

        public UserController(IIdeasRepository ideasRepository, IAuthentification auth, IDbSelector dbSelector)
         {
            this.Repository = ideasRepository;
            this.Auth = auth;
            this.DbSelector = dbSelector;
         }

        protected override void Initialize(System.Web.Routing.RequestContext requestContext)
        {
            base.Initialize(requestContext);
            ViewBag.Author = CurrentAuthor;
        }

        public LoggedinAuthor CurrentAuthor
        {
            get
            {
                Auth.HttpContext = this.HttpContext.ApplicationInstance.Context;
                var currentUser = Auth.CurrentUser;
                if (currentUser != null)
                {
                    return ((UserIndentity)currentUser.Identity).User.ToLoggedinAuthor();
                }
                return null;
            }
        }
      
        [HttpGet]
        public ActionResult IdeasList(int page = 1)
         {
             IdeasListViewModel model = DbSelector.GetIdeasList(Repository, page, PageSize); 
            
             return View(model);
         }
        
        [HttpGet]
        public ActionResult UserPage(int userId)
         {
             Author author = Repository.GetAuthor(userId);

             return View(author);
         }

        [HttpGet]
        public ActionResult EditIdea(int ideaId)
         {
             Idea idea = DbSelector.GetIdea(Repository, ideaId);
             
             return View(idea);
         }

         [HttpPost]
         public ActionResult EditIdea(Idea idea)
         {
             if (idea.UserId == CurrentAuthor.UserId)
             {
                 if (ModelState.IsValid)
                 {
                     Repository.SaveIdea(idea);
                     TempData["message"] = string.Format("{0} has been saved", idea.Title);
                     return RedirectToAction("IdeasList");
                 }
                 else
                 {
                     return View(idea);
                 }
             }

             return RedirectToAction("IdeasList");
         }
        [HttpGet]
         public ActionResult CreateIdea()
         {
             return View("EditIdea", new Idea { UserId = CurrentAuthor.UserId, Date = DateTime.Now, Status = IdeaStatus.IS_ACTIVE});
         }
        [HttpGet]
        public ActionResult MoveIdeaToTrash(int ideaId)
         {
             Repository.MoveIdeaToTrash(ideaId);

             return RedirectToAction("IdeasList");
         }

        [HttpGet]
         public ActionResult DeleteComment(int commentId)
         {
             Repository.DeliteComment(commentId);

             return RedirectToAction("IdeasList");
         }
        [HttpGet]
         public ActionResult GetIdeaFromTrash(int ideaId)
         {
             Repository.GetIdeaFromTrash(ideaId);

             return RedirectToAction("Trash");
         }

        [HttpGet]
        public ActionResult DeleteIdea(int ideaId)
        {
            Repository.DeliteIdea(ideaId);

            return RedirectToAction("Trash");
        }
        [HttpGet]
         public ViewResult Trash(int page = 1)
         {
             IdeasListViewModel model = DbSelector.GetIdeasTrashList(Repository, page, PageSize);
             
             return View(model);
         }


        [HttpGet]
        public ViewResult CommentsList(int page = 1)
         {
             CommentsListViewModel model = DbSelector.GetCommentsList(Repository, page, PageSize);
             
             return View(model);
         }
    }
}

WebUI/Views/Shared/_Layout.cshtml
@using WebUI.Auth

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/Site.css" type="text/css" rel="stylesheet" />
    <link href="~/Content/simple-line-icons.css" type="text/css" rel="stylesheet" />

</head>
<body>
        <div id="header">
            <div class="title">
                @Html.ActionLink("IDEAS REPOSITORY", "IdeasList", "Ideas")
            </div>
            
            @{LoggedinAuthor currentAuthor = (LoggedinAuthor)ViewBag.Author;}
            @if (currentAuthor == null)
            {
                <div class="login">
                    @Html.ActionLink(" ",
                            "Login",
                                     "Account",
                            null,
                            new { @class = "icon-user", title = "Login"}
                            )
                </div>
                <div class="login">
                    @Html.ActionLink("Check In",
                            "CheckIn",
                                     "Account",
                            null,
                            new { title = "Check In" }
                            )
                </div>
            }
            else {
                <div class="login">
                    @Html.ActionLink(@currentAuthor.Name,
                                "UserPage",
                                         "Ideas",
                                 new { login = @currentAuthor.Login},
                                new { title = "Profile"}
                                )
                </div>
                <div class="login">
                    @Html.ActionLink("Log out",
                                "LogOut",
                                         "Account",
                                null,
                                new { title = "Log out" }
                                )
                </div>
            }
            
        </div >
        
    <div id="content">
        @RenderBody()
    </div>
    
</body>
</html>

WebUI/Views/Shared/_UserLayout.cshtml
@using WebUI.Auth

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/User.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/simple-line-icons.css" type="text/css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div id="header">
        <div class="title">
        @Html.ActionLink("IDEAS REPOSITORY", "IdeasList", "User")
        </div>
        @{LoggedinAuthor currentAuthor = (LoggedinAuthor)ViewBag.Author;}
        @if (currentAuthor == null)
        {
            <div class="login">
                @Html.ActionLink(" ",
                            "Login",
                                     "Account",
                            null,
                            new { @class = "icon-user", title = "Login" }
                            )
            </div>
            <div class="login">
                @Html.ActionLink("Check In",
                            "CheckIn",
                                     "Account",
                            null,
                            new { title = "Check In" }
                            )
            </div>
        }
        else
        {
            <div class="login">
                @Html.ActionLink(@currentAuthor.Name,
                                "UserPage",
                                         "Ideas",
                                 new { login = @currentAuthor.Login },
                                new { title = "Profile" }
                                )
            </div>
            <div class="login">
                @Html.ActionLink("Log out",
                                "LogOut",
                                         "Account",
                                null,
                                new { title = "Log out" }
                                )
            </div>
        }
        <div >
            <ul class="horisontal-menu ">
                <li>
                    @Html.ActionLink(" ", "Trash", "User", new { @class = "button icon-trash" })
                </li>
                <li>
                    @Html.ActionLink("Ideas", "IdeasList", "User", new { @class = "button" })
                </li>
                <li>
                    @Html.ActionLink("Comments", "CommentsList", "User", new { @class = "button" })
                </li>
            </ul>
        </div>
    </div>
    <div id="content">
        @RenderBody()
    </div>
</body>
</html>